# Generated by Django 5.2.4 on 2025-12-07 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='owned_categories',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='planned_events',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='todos',
        ),
        migrations.AlterField(
            model_name='plannedevent',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_events', to='app.profile'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='app.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='recurrencerule',
            unique_together={('type', 'interval', 'count', 'until')},
        ),
    ]
